// Generated by scripts/build-project-pages.js from the approved records. Do not edit by hand.
window.PROJECTS_DATA = [
  {
    "id": "three-little-pigs",
    "title": "3 Little Pigs Wall Assembly",
    "year": "2025",
    "category": "FAA 330",
    "description": "A straw-bale wall assembly that ordinary builders can put up: conventional stick framing, R-52 insulation.",
    "image": "images/tour/tlp-axon.jpg",
    "link": "projects/three-little-pigs.html"
  },
  {
    "id": "para-la-tierra",
    "title": "Anthropogenic Effects of Construction on Freshwater Aquatic Biodiversity",
    "year": "2024",
    "category": "ecology",
    "description": "Four months of river fieldwork in Pilar, Paraguay, testing whether building the Costanera changed the fish and invertebrates living there.",
    "image": "images/tour/plt-canoe.jpg",
    "link": "projects/para-la-tierra.html"
  },
  {
    "id": "beavers-burden",
    "title": "Beaver's Burden",
    "year": "2025",
    "category": "ARCH 172",
    "description": "Gizmo architecture that works alongside beavers to rewild the Kankakee Marsh: something you wear, a boat, and a field of shipping-container-sized interventions.",
    "image": "images/tour/bb-standing.jpg",
    "link": "projects/beavers-burden.html"
  },
  {
    "id": "mylo-to-go",
    "title": "Mylo To-Go",
    "year": "2025",
    "category": "ArtD 326",
    "description": "Takeout containers grown from mycelium rather than manufactured, designed to replace single-use Styrofoam and decompose without a trace.",
    "image": "images/tour/mylo-picnic.jpg",
    "link": "projects/mylo-to-go.html"
  },
  {
    "id": "uss-lead-revival",
    "title": "The Dark Side of Chicago · USS Lead (ARCH 273)",
    "year": "2025",
    "category": "ARCH 273",
    "description": "A semester on East Chicago's USS Lead Superfund site: a time-bending atlas, gable prototypes that dunes could grow on, a village modeled on Dutch dikes, and a hundred-year story told by birds and wind.",
    "image": "images/tour/a273-atlas.jpg",
    "link": "projects/uss-lead-revival.html"
  },
  {
    "id": "genealogy-of-a-beaver-dam",
    "title": "Genealogy of a Beaver Dam",
    "year": "2025",
    "category": "ArtD 326",
    "description": "A construction manual for a building made by beavers: its materials, site, foundation and walls, drawn the way you'd document human architecture.",
    "image": "images/tour/gbd-cover.jpg",
    "link": "projects/genealogy-of-a-beaver-dam.html"
  }
];
